<h2>Welkom bij Patisserie Van Gorp</h2>
<p>Een stijlvol interieur in combinatie met de geur van versgebakken brood en andere ambachtelijke producten.
Respect voor kwaliteit, rekening houdend met het goede van vroeger. Dat is waar wij voor staan.</p>

<p>Als aanvulling bieden wij u een verstoog met groot assortiment charcuterie en kaas.
Kris, zijn vrouw Wendy en hun dochter Maxime heten u van harte welkom op hun site en bedanken u voor uw interesse.</p>

<!-- news region if requested -->
<div class="n-news">
  <h3>Jaarlijks verlof</h3>
  <img src="dist/images/content/holiday.png" alt="verlof">
  <p>Dit enkel om te tonen hoe extra informatie getoond wordt.</p>
  <p>we zijn er even tussen uit, op 15 augustus zijn we er weer.</p>
</div>