<h2>Welkom bij Patisserie Van Gorp</h2>
<p>Een stijlvol interieur in combinatie met de geur van versgebakken brood en andere ambachtelijke producten.
Respect voor kwaliteit, rekening houdend met het goede van vroeger. Dat is waar wij voor staan.</p>

<p>Als aanvulling bieden wij u een verstoog met groot assortiment charcuterie en kaas.
Kris, zijn vrouw Wendy en hun dochter Maxime heten u van harte welkom op hun site en bedanken u voor uw interesse.</p>