<h2 class="heading-two">Patesserie Van Gorp <span>Privacyverklaring</span></h2>
<p>PERSOONSGEGEVENS DIE WORDEN VERWERKT</p>

<p>Patesserie Van Gorp kan persoonsgegevens over u verwerken, doordat u gebruik maakt van de diensten van Patesserie Van Gorp en/of omdat u deze zelf bij het invullen van een contactformulier op de website aan Patesserie Van Gorp verstrekt. Patesserie Van Gorp kan de volgende persoonsgegevens verwerken:</p>

<p>- Uw voor- en achternaam</p>

<p>- Uw telefoonnummer</p>

<p>- Uw e-mailadres</p>

<p>WAAROM Patesserie Van Gorp GEGEVENS NODIG HEEFT</p>

<p>Patesserie Van Gorp verwerkt uw persoonsgegevens om telefonisch contact met u op te kunnen nemen als u daar om verzoekt, en/of om u schriftelijk (per e-mail en/of per post) te kunnen benaderen indien u telefonisch onverhoopt niet bereikt kunt worden.</p>

<p>Daarnaast kan Patesserie Van Gorp uw persoonsgegevens gebruiken in het kader van het uitvoeren van een met u gesloten overeenkomst van opdracht, doorgaans bestaande uit juridische dienstverlening.</p>

<p>HOE LANG Patesserie Van GorpPatesserie Van Gorp GEGEVENS BEWAART</p>

<p>Patesserie Van Gorp bewaart uw persoonsgegevens niet langer dan strikt nodig is om de doelen te realiseren, waarvoor uw gegevens worden verzameld. Uw gegevens worden niet langer dan een jaar bewaard indien er geen overeenkomst met u tot stand komt.</p>

<p>DELEN MET ANDEREN</p>

<p>Patesserie Van Gorp verstrekt uw persoonsgegevens alléén aan derden indien dit nodig is voor de uitvoering van een overeenkomst met u, of om te voldoen aan een wettelijke verplichting.</p>

<p>Privacyverklaring</p>

<p>IN KAART BRENGEN WEBSITEBEZOEK</p>

<p>Op de website van Patesserie Van Gorp worden algemene bezoekgegevens bijgehouden, waaronder het IP-adres van uw computer en het tijdstip van opvraging en gegevens die uw browser meestuurt.&nbsp;</p>

<p>Deze gegevens worden gebruikt voor analyses van bezoek- en klikgedrag op de website. Patesserie Van Gorp gebruikt deze informatie om de werking van de website te verbeteren.&nbsp;</p>

<p>Deze gegevens worden zo veel mogelijk geanonimiseerd en worden niet aan derden verstrekt.</p>

<p>GOOGLE ANALYTICS</p>

<p>Patesserie Van Gorp maakt gebruik van Google Analytics om bij te houden hoe gebruikers de websitegebruiken en hoe effectief de Adwords-advertenties van Patesserie Van Gorp bij Google zoekresultaatpagina’s zijn.</p>

<p>De aldus verkregen informatie wordt, met inbegrip van het adres van uw computer (IP-adres), overgebracht naar en door Google opgeslagen op servers in de Verenigde Staten.&nbsp;</p>

<p>Lees het privacybeleid van Google voor meer informatie. U treft ook het privacybeleid van Google Analytics hier aan.</p>

<p>Google gebruikt deze informatie om bij te houden hoe onze website gebruikt wordt, om rapporten over de Website aan Patesserie Van Gorp te kunnen verstrekken en om haar adverteerders informatie over de effectiviteit van hun campagnes te kunnen bieden.</p>

<p>Google kan deze informatie aan derden verschaffen indien Google hiertoe wettelijk wordt verplicht, of voor zover deze derden de informatie namens Google verwerken.</p>

<p>Patesserie Van Gorp heeft hier geen invloed op.</p>

<p>Patesserie Van Gorp heeft Google geen toestemming gegeven om via Patesserie Van Gorp verkregen Analytics-informatie te gebruiken voor andere Google-diensten.</p>

<p>GEGEVENS INZIEN, AANPASSEN OF VERWIJDEREN</p>

<p>U heeft het recht om uw persoonsgegevens in te zien, te corrigeren of te verwijderen. U kunt een verzoek tot inzage, correctie of verwijdering aanvragen via ons e-mail adres.</p>

<p>Patesserie Van Gorp zal zo snel mogelijk, maar binnen vier weken, op uw verzoek reageren.</p>

<p>&nbsp;</p>

<p>BEVEILIGEN</p>

<p>Patesserie Van Gorp neemt de bescherming van uw gegevens serieus en neemt passende maatregelen om misbruik, verlies, onbevoegde toegang, ongewenste openbaarmaking en ongeoorloofde wijziging tegen te gaan.&nbsp;</p>

<p>De website van Patesserie Van Gorp maakt gebruik van een betrouwbaar SSL Certificaat om te borgen dat uw persoonsgegevens niet in verkeerde handen vallen.</p>

<p>Als u de indruk heeft dat uw gegevens niet goed beveiligd zijn of er aanwijzingen zijn van misbruik, of indien u meer informatie wenst over de beveiliging van door Patesserie Van Gorp verzamelde persoonsgegevens, neem dan contact met Patesserie Van Gorp op via het contactformulier. https://www.patisserie-vangorp.be/ is een website van Patesserie Van Gorp.&nbsp;</p>

<p>Patesserie Van Gorp is als volgt te bereiken:</p>

<p>Postadres: Sint-Jozeflaan 33 2400 Mol-Wezel</p>

<p>Inschrijvingsnummer handelsregister Kamer van Koophandel: BE</p>

<p>Telefoon: (+32) 014811260</p>
