<h2>Zuurdesembrood</h2> 

<img src="../../dist/images/content/zuurdesembrood.jpg" alt="zuurdesembrood">

<p>Eerlijk, puur, lekker en gezond. Alleen de beste ingrediënten zijn goed genoeg.</p>

<p>Patisserie Van Gorp is één van de pioniers in de streek als het gaat om zuurdesembrood. Brood bakken zoals het bedoeld is. Al onze broden worden gebakken op basis van zuurdesem. </p>
<p>Wat is desem?</p>
<p>Het is een brooddeeg dat wordt gemaakt zonder toevoeging van gist. Fermentatie of vergisting is noodzakelijk voor het rijzen van het deeg. Fermentatie vindt plaats dankzij melkzuurbacterieën en gisten die van nature in het deeg aanwezig zijn. Deze bacterieën zorgen er onder andere voor dat er vorming van koolzuurgas ontstaat die bij het bakken het brood een luchtige structuur geven.</p>
<p>Het belangrijkste ingrediënt is TIJD. Ons brood is bijna een etmaal onderweg. Ter vergelijking met een gistbrood van bij bakker of supermarkt: een gistbrood rijst hooguit 2 uur. Gist zorgt voor te snel rijzen. Dat gaat ten koste van 300 aroma’s die zuurdesem ontwikkelt. Tijdens het lange rijzen kan de smaak ontwikkelt worden. Bij een niet-zuurdesembrood worden broodverbeteraars toegevoegd om het gebrek aan smaak te compenseren.</p>
<p>Ons zuurdesem is NIET zuur. Door de lange bereidingstijd is de zure smaak bijna helemaal verdwenen.</p>